### ISSUE TITLE
global namespace would be polluted

### ISSUE THREAD

**Issue by cxwithyxy** [smith/namespacedotjs#2]
```
Namespace("aa",{"ffff":2222})

console.log(window["ffff"])
// undefined

Namespace.use("aa.*",function (){console.log(ffff * 1000)})

console.log(window["ffff"])
// 2222
```
after **Namespace.use** has been calling, **ffff** was became a **global variable**

**Comment by smith** [comment]
Thanks for reporting. This repository is no longer maintained and you should use pretty much any other module system instead.
